# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Infrastructure
  licenses: Apache-2.0
  images: |
    - name: seaweedfs
      image: docker.io/bitnami/seaweedfs:3.64.0-debian-12-r0
apiVersion: v2
appVersion: 3.64.0
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - seaweedfs-database
    version: 18.x.x
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
description: SeaweedFS is a fast distributed storage system for blobs, objects, files, and data lake, for billions of files!
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/seaweedfs/img/seaweedfs-stack-220x234.png
keywords:
  - seaweedfs
  - storage
  - blob-storage
  - file-storage
  - object-storage
  - s3
maintainers:
  - name: VMware, Inc.
    url: https://github.com/bitnami/charts
name: seaweedfs
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/seaweedfs
version: 0.1.0
